### PR TITLE
Infer params

### PR DESCRIPTION
**Pull request by k1o0**
The new inferParameters function uses the VoidSignal class to explore the expDef.

The new inferParameters is much quicker: 0.2 vs 0.85 / 0.25 vs 1.1s for advancedChoiceWorld and choiceWorld respectively (for the latter the main reason is that no functions in the expDef are run in the new inferParameters).

One difference between the two functions: in the new inferParameters, if you subassign a parameter, it becomes a param.  In the old version the parameter had to be subreferenced in order for it to work.  We may want to restore that behaviour before merging.

Another note: there may be a better way to run the performance test.  Any ideas?  Is it easy to make one test script that you can run 'runtests' and 'runperf' on?

### CODE REVIEW

**Comment by jaib1** [comment]
> One difference between the two functions: in the new inferParameters, if you subassign a parameter, it becomes a param. In the old version the parameter had to be subreferenced in order for it to work. We may want to restore that behaviour before merging.

Why would we want to restore this?

**Comment by jaib1** [comment]
it seems there is a conflict between this branch's 'signals' submodule, and 'dev' 'signals' submodule. Am I fine to pull 'dev' 'signals' submodule into this branch before merging?

**Comment by k1o0** [comment]
Well I made some changes to the signals repo in order for it to work, but I'm not sure what branch.  I'l look into it...

**Comment by jaib1** [comment]
done via command line

**Pull request merged**
