### PR TITLE
2016b mc upgrade

### PR DESCRIPTION
**Pull request by k1o0**
Version of mc compatible with 2016b + a few minor changes

### CODE REVIEW

**Comment by k1o0** [comment]
had to use for loops in three places as cellfun doesn't work well with object arrays and behaves differently when called anonymously.  There may be a better work around, especially at the bottom of saveParamProfile!

**Comment by nsteinme** [comment]
Hey Miles, this PR is very difficult to review because there are 338 changed files. 

Most of these are from Chris's mercurial repository in cb-tools - could you delete that? 
Others are .DS_Store and junk like that. I have added a .gitignore file to the repository so it won't find those in the future. 

If you delete the mercurial folders (and any other junk files you see) and commit those changes then push again, I will review it. Sorry to be slow! I'll take a look at the for loops and see if I have any ideas - but I'm not nearly so opposed to for loops as chris was :)

**Comment by k1o0** [comment]
At some point let's remove all of the third party packages from that directory and replace them with installation instructions (I've already done this with the GUI Layout Toolbox) and remove the files that aren't relevant (e.g. urlread2?).  I've removed the MercuryDialog folder but I don't know about the others.  I haven't added any of my own files, only changed some that were already there so you can skip the added files.

**Comment by nsteinme** [comment]
That's a great idea. Do you think we can already do it for /cb-tools/jsonlab, /cb-tools/SuperWebSocket, and /cb-tools/java?

Here are the instructions for jsonlab:
```
% install https://uk.mathworks.com/matlabcentral/fileexchange/33381-jsonlab--a-toolbox-to-encode-decode-json-files
%  -- (download tooolbox and run it)
```

If you could take a quick look around and figure out whether there are also easy instructions for SuperWebSocket and java, that would be great. If it's not easy or you can't find it, then no problem, we can leave those files in the repository for now.

**Comment by k1o0** [comment]
1. The java directory looks bespoke to me.  It's certainly not simply a java websocket distro.  
2. JSONlab can probably be taken out (the new version is for >=2014b).  A cursory look at the code seems to suggest that urlread2 and jasonlab were part of Chris's attempt to implement posting to Google Sheets.  I have a feeling they can be removed altogether but we best confirm with Chris.
3. SuperWebSocket I would leave as currently none of us would be able to fix things if a new version broke expServer.

**Comment by nsteinme** [comment]
Hi Miles, I just tried to test this but failed with the error below. I'm fairly certain I'm correctly using the code in this pull request, for example, the comment at the top of my eui.MControl does now say "Master" rather than "Mission/Mouse/Matteo??". I think it is possible that the problem is in which version of uiextras is being used? I've got:

```
>> which uiextras.VBox
\\zserver\Code\Rigging\cb-tools\GUILayout\+uiextras\VBox.m  % uiextras.VBox constructor

```
and I checked, there is no \cb-tools\GUILayout in this repository. If you made changes to the uiextras code that are necessary to run this, could you either let me know which repository those are in (or how to install them) or else move them into this repository? Or do you have any other ideas about what is going wrong? Thanks!

The error I got:

```
>> mc
MControl destructor called
Error using uiextras.Container (line 66)
Trying to run using double-handle MATLAB graphics against the new graphics system. Please re-install.

Error in uiextras.Box (line 38)
            obj@uiextras.Container( varargin{:} );

Error in uiextras.VBox (line 44)
            obj@uiextras.Box( varargin{:} );

Error in eui.MControl/buildUI (line 428)
      obj.RootContainer = uiextras.VBox('Parent', parent,...

Error in eui.MControl (line 73)
      obj.buildUI(parent);

Error in mc (line 14)
h = eui.MControl(f);
```

**Comment by k1o0** [comment]
Did you install GUI Layout Toolbox and check that the paths to the toolbox are higher than those to zserver? Ideally you should have all of the zserver Rigbox paths removed except those for signals.  I wrote some instructions about installing the new Rigbox in the readme.  Also when you added the paths it should have checked whether you had the new toolbox installed.  Let me know if the error persists.

**Comment by nsteinme** [comment]
K thanks, I missed the readme. You an assert that requires 2016b but is
that true? Any version with the new graphics should work, right, 2014b or
later? I am on 2015a here, would rather not upgrade right now...

**Comment by nsteinme** [comment]
Ok, so do you know whether this github repository is currently used at any rigs? The fact that the new GUILayout just makes fields at the bottom of parameditor disappear rather than squeezing them all in makes this so far un-usable, doesn't it? Is there a workaround? If this repository isn't used at any rigs yet then I'll continue reviewing and merge, and make a new issue to fix that. But if it's currently in use then we can't merge yet.

**Comment by nsteinme** [comment]
Ok ok, sorry for all the messages. I made the global panel scrollable. There are a couple improvements that should happen with it but it works for now. Will continue to review the rest of this later. Sorry to be slow on it. 

By the way have you tried this at a rig yet or just at your desktop computer? You or I should test it on a real rig at least briefly before we're good with it. I can probably do that soon if you haven't already. 

Thanks!

**Comment by nsteinme** [comment]
Looks good, thanks very much for doing this!

**Pull request merged**
