### PR TITLE
Dev images

### PR DESCRIPTION
**Pull request by kevin-j-miller**
Update Dev to point to the new signals-dev, which has the changes to image handling.

### CODE REVIEW

**Comment by k1o0** [comment]
@jaib1 just merged another branch into dev.  Want to re-add the signals module at the latest dev commit?

**Comment by k1o0** [comment]
Actually, it would be good to merge the AlyxTest branch into alyx-matlab/dev then add the latest dev commit for that submodule too.

**Comment by jaib1** [comment]
> Actually, it would be good to merge the AlyxTest branch into alyx-matlab/dev

do you mean the branch 'alyx-matlab/tests' into 'alyx-matlab/dev' ? I don't see an issue with adding the recently updated 'signals/dev' submodule (after both the 'images' and 'voidsignal_fix' merges) to 'Rigbox' while I wait for @k1o0  regarding the 'alyx-matlab/tests' branch?

**Comment by jaib1** [comment]
this has been done in the command line by adding the updated 'signals' submodule directly to 'Rigbox/dev', instead of merging this branch

**Pull request closed without merging**
