### PR TITLE
added future training flag to AlyxPanel

### PR DESCRIPTION
**Pull request by jaib1**

### CODE REVIEW

**Comment by k1o0** [comment]
This is very hard to review :/ Did you change the order of the methods or did do something weird?  It seems to think ever line was changed

**Comment by jaib1** [comment]
ah, did smart-indent on the file = D

**Comment by k1o0** [comment]
That makes sense.  I change my smart indent to be 2 spaces instead of four.  Four seems like too much to me.  It bugs me about Python too...

**Comment by jaib1** [comment]
haha I was wondering when we'd get to the difference in stylistic preferences...

**Comment by k1o0** [comment]
I also prefer spaces around equals signs because it improves readability, and try to use as informative variable names as possible, even if they're quite long.  Particularly if it doesn't cause a line to run on there's no disadvantage to having long variable names.  When Pip first joined the lab all of his variables were four letters long and no one could read his code.

**Comment by jaib1** [comment]
hmm, yeah I sometimes don't do the whitespace around expression bindings because some languages don't read it, and I prefer shorter variable names, though I almost always explain all variable names in a comment

**Comment by jaib1** [comment]
updated as per your request

**Pull request merged**
