### PR TITLE
Usability tweaks to MC

### PR DESCRIPTION
**Pull request by kevin-j-miller**
I added my changes to MC into a fresh branch, and tested that branch on the MC computer in the behavior room. The changes seem to work, and the machine seems to be able to run experiments properly. Please let me know if this looks good to you guys, or if there are more tests that I should do.

### CODE REVIEW

**Comment by jaib1** [comment]
looks good to me! but there may be a reason why 'AlyxPanel' should be kept private in 'MControl'? So I'll wait for Miles

**Comment by k1o0** [comment]
Looks good, my two suggestions before approving:

1. Wherever possible restrict unnecessary access: couldn't the AlyxPanel property be moved to the private set access attribute block?
2. The rig_scripts directory should be removed from the repo and instead either be on zserver or in the cortexlab directory of the Rigbox repo.  I would prefer the former myself.

Also I'm not sure how to merge this without changing the submodule tree.  @jaib1 do you know how to do this properly?

**Comment by kevin-j-miller** [comment]
Thanks for the comments! I'm at DM today, but I'll clean this up tomorrow
when I'm in lab.

1. I'm not sure what this means -- I guess I'm a little fuzzy on how
objects and access works in Matlab. The goal was for *start_alyx_mc.bat*
file to be able to tell mc to log in to Alyx.  Maybe a more conservative
way to accomplish this would be to hide mc.AlyxPanel, but write a new
public method called mc.login that points to mc.AlyxPanel.login? Let me
know what you think is best, and I'll figure out how to do it.

2. Sounds good, I'll do that

**Comment by jaib1** [comment]
> 1. I'm not sure what this means -- I guess I'm a little fuzzy on how objects and access works in Matlab.

I can show you this tomorrow, Kevin, it's a simple fix. 

> Also I'm not sure how to merge this without changing the submodule tree. @jaib1 do you know how to do this properly?

In this case since the alyx-matlab submodule is also being updated, don't we want to merge into Rigbox with Rigbox pointing to the new alyx-matlab commit (which will be the tree) ?

**Comment by k1o0** [comment]
> 1. I'm not sure what this means -- I guess I'm a little fuzzy on how objects and access works in Matlab.

You moved AlyxPanel to the unrestricted properties block, however you should be able to move it to the block where only the [set access is private](https://github.com/cortex-lab/Rigbox/blob/master/%2Beui/MControl.m#L33) and still be able to call the login method:
```
properties
    LoggingDisplay % control for showing log output
end
  
properties (SetAccess = private)
    ParamEditor
    ...
    AlexPanel
end

```
RE the merge: The issue is that there are updates to both Rigbox and alyx-matlab and when we merge we need to first merge 'dev-kevin' into 'dev' on alyx-matlab, then do the same for Rigbox but with the submodule commit changed to be the latest dev commit.  The question is how to do this in the simplest and clearest way.

**Comment by jaib1** [comment]
> RE the merge: ...
Right, if I understand this correctly, when 'dev-kevin' is merged into 'dev' on 'alyx-matlab', followed by 'dev-kevin' being merged into 'dev' on 'Rigbox', 'Rigbox' will automatically point to the latest commit (tree) on 'alyx-matlab' 'dev', because the commit to 'Rigbox' will include the 'alyx-matlab' submodule.

**Pull request merged**
